-- Atomic payment processing for process-payment edge function.
-- Replaces the JS-side multi-step inserts + manual soft-delete rollback
-- (supabase/functions/process-payment/index.ts) with a single plpgsql
-- function. The function body is atomic: any exception (bad amount, missing
-- invoice, FK violation...) rolls back every insert/update automatically.
-- Concurrency: invoices are locked with `select ... for update` so two
-- simultaneous payments against the same invoice serialize instead of
-- racing on a stale paid_amount.

create or replace function public.process_payment_tx(
  p_student_id uuid,
  p_amount numeric,
  p_payment_method text,
  p_payment_type text,
  p_recorded_by uuid,
  p_course_id bigint default null,
  p_invoice_ids bigint[] default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_payment payments%rowtype;
  v_invoice invoices%rowtype;
  v_invoice_id bigint;
  v_share numeric;
  v_new_paid numeric;
begin
  -- Defense in depth: the edge function validates too, but never trust only
  -- the caller for financial writes.
  if p_amount is null or p_amount <= 0 then
    raise exception 'Amount must be positive';
  end if;

  -- 1. Insert the payment row (receipt_number is generated by column default)
  insert into payments (student_id, amount, payment_method, payment_type, recorded_by, course_id)
  values (p_student_id, p_amount, p_payment_method::payment_method, p_payment_type::payment_type, p_recorded_by, p_course_id)
  returning * into v_payment;

  -- 2. Insert the matching transaction, referencing the new receipt_number
  insert into transactions (student_id, type, amount, reference, recorded_by)
  values (p_student_id, 'payment', p_amount, v_payment.receipt_number, p_recorded_by);

  -- 3. Allocate the payment across the given invoices (row-locked so
  --    concurrent payments serialize). An unknown invoice id aborts the
  --    whole function and rolls everything back.
  if p_invoice_ids is not null and cardinality(p_invoice_ids) > 0 then
    v_share := p_amount / cardinality(p_invoice_ids);

    foreach v_invoice_id in array p_invoice_ids loop
      select * into v_invoice
      from invoices
      where id = v_invoice_id and deleted_at is null
      for update;

      if not found then
        raise exception 'Invoice % does not exist', v_invoice_id;
      end if;

      -- Clamp at total_amount: never let paid_amount silently exceed it.
      v_new_paid := least(coalesce(v_invoice.paid_amount, 0) + v_share, v_invoice.total_amount);

      update invoices
      set paid_amount = v_new_paid,
          status = case
            when v_new_paid >= v_invoice.total_amount then 'paid'::invoice_status
            else 'partially_paid'::invoice_status
          end,
          updated_at = now()
      where id = v_invoice_id;
    end loop;
  end if;

  -- 4. Notify the student
  insert into notifications (user_id, title, message, type, category)
  values (
    p_student_id,
    'Paiement reçu',
    'Paiement de ' || to_char(p_amount, 'FM999G999G999') || ' DA reçu (' || p_payment_method || ')',
    'success',
    'payment'
  );

  return jsonb_build_object('success', true, 'payment', to_jsonb(v_payment));
end;
$$;

-- Financial write function: service_role only (the edge function holds the
-- service role key). Never callable directly from a client.
revoke all on function public.process_payment_tx(uuid, numeric, text, text, uuid, bigint, bigint[]) from public, anon, authenticated;
grant execute on function public.process_payment_tx(uuid, numeric, text, text, uuid, bigint, bigint[]) to service_role;
